# Generated by Django 6.0 on 2025-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='is_working',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='department',
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
