# Generated by Django 6.0 on 2025-12-15 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_doctorprofile_patientprofile_delete_user'),
        ('strikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strike',
            name='patient',
        ),
        migrations.AddField(
            model_name='strike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strike',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_strikes', to='accounts.doctorprofile'),
            preserve_default=False,
        ),
    ]
