# Generated by Django 6.0 on 2025-12-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Название болезни')),
                ('medications', models.JSONField(help_text='[{name, dose, usage}]', verbose_name='Лекарства')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выписки')),
                ('treatment_duration_days', models.PositiveIntegerField(verbose_name='Срок лечения (дни)')),
                ('system_recommendations', models.JSONField(default=list, help_text="['Постельный режим', 'Пить больше воды']", verbose_name='Рекомендации системы')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctorprofile')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.visithistory')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
    ]
