# Generated by Django 6.0 on 2025-12-15 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalprescription',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='disease_name',
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='system_recommendations',
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='treatment_duration_days',
        ),
        migrations.RemoveField(
            model_name='medicalprescription',
            name='visit',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='description',
            field=models.TextField(default='Не указано'),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
