# Generated by Django 6.0 on 2025-12-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_doctorprofile_patientprofile_delete_user'),
        ('appointments', '0001_initial'),
        ('prescriptions', '0002_alter_medicalprescription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='Не указано'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile'),
        ),
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
